filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
      - drop_event.when:
          equals:
            container.name: "filebeat" # optional, to ignore filebeat logs itself

# Optional global fields
fields:
  environment: dev

# Output to Logstash
output.logstash:
  hosts: ["logstash:5044"]

# Optional: monitoring
monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]

logging.level: info
logging.to_files: false # disables file logging
logging.to_syslog: false
logging.to_console: true