// src/app/layout.tsx
// import type { Metadata } from 'next';
import './globals.css';
import { LoggedUserNameProvider } from '@/context/LoggedUserNameContext';
import { SelectedUserNameProvider } from '@/context/SelectedUserNameContext';
import { LoggedUserIdProvider } from '@/context/UserIdContext';

const BG_URL = 'https://images6.alphacoders.com/134/1344450.jpeg';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`relative bg-cover bg-center bg-no-repeat`}
        style={{ backgroundImage: `url('${BG_URL}')` }}
      >
        <LoggedUserNameProvider>

          <SelectedUserNameProvider>

            <LoggedUserIdProvider>

            <main className="relative bg-cover bg-center bg-no-repeat"
            style={{ backgroundImage: `url('${BG_URL}')` }}
            >
              {children} {/* This renders the content of your page.tsx files */}
            </main>

          </LoggedUserIdProvider>

          </SelectedUserNameProvider>
          
      </LoggedUserNameProvider>
    </body>
  </html>
  );
}