# services:
#   # ---------------------------
#   # Frontend
#   frontend:
#     build: ./frontend
#     container_name: frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - auth-service
#       - chat-service
#       - dashboard-service
#       - db-service
#       - ping-pong-service
#       - parcheesi-service
#       - user-service
#     networks:
#       - monitoring

#   # ---------------------------
#   # Backend Services
#   auth-service:
#     build: backend/auth-service
#     container_name: auth-service
#     ports:
#       - "5001:5001"
#     networks:
#       - monitoring
#     environment:
#       - SECRET_KEY=mysecretkey

#   chat-service:
#     build: backend/chat-service
#     container_name: chat-service
#     ports:
#       - "5003:5003"
#     networks:
#       - monitoring

#   dashboard-service:
#     build: backend/dashboard-service
#     container_name: dashboard-service
#     ports:
#       - "5002:5002"
#     networks:
#       - monitoring

#   db-service:
#     build: backend/db-service
#     container_name: db-service
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./backend/db-service/src/db:/app/src/db   # persistance sqlite
#     networks:
#       - monitoring

#   ping-pong-service:
#     build: backend/ping-pong-service
#     container_name: ping-pong-service
#     ports:
#       - "5500:5500"
#     networks:
#       - monitoring

#   parcheesi-service:
#     build: backend/parcheesi-service
#     container_name: parcheesi-service
#     ports:
#       - "5555:5555"
#     networks:
#       - monitoring
#   user-service:
#     build: backend/User-Service
#     container_name: user-service
#     ports:
#       - "5004:5004"
#     networks:
#       - monitoring   

#   # ---------------------------
#   # Prometheus
#   prometheus:
#     image: prom/prometheus
#     container_name: prometheus
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
#     networks:
#       - monitoring

#   # ---------------------------
#   # Grafana
#   grafana:
#     image: grafana/grafana
#     container_name: grafana
#     ports:
#       - "4000:3000"
#     environment:
#       - GF_SECURITY_ADMIN_USER=admin
#       - GF_SECURITY_ADMIN_PASSWORD=admin
#     networks:
#       - monitoring
#     volumes:
#       - grafana_data:/var/lib/grafana

# # ---------------------------
# networks:
#   monitoring:
#     driver: bridge

# volumes:
#   grafana_data:
#   prometheus_conf:
#     driver: local



# services:
#   # ---------------------------
#   # Frontend
#   frontend:
#     build: ./frontend
#     container_name: frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - auth-service
#       - chat-service
#       - dashboard-service
#       - db-service
#       - ping-pong-service
#       - parcheesi-service
#       - user-service
#     networks:
#       - monitoring
#     logging:
#       driver: json-file

#   # ---------------------------
#   # Backend Services
#   auth-service:
#     build: backend/auth-service
#     container_name: auth-service
#     ports:
#       - "5001:5001"
#     networks:
#       - monitoring
#     environment:
#       - SECRET_KEY=mysecretkey
#     logging:
#       driver: json-file

#   chat-service:
#     build: backend/chat-service
#     container_name: chat-service
#     ports:
#       - "5003:5003"
#     networks:
#       - monitoring
#     logging:
#       driver: json-file

#   dashboard-service:
#     build: backend/dashboard-service
#     container_name: dashboard-service
#     ports:
#       - "5002:5002"
#     networks:
#       - monitoring
#     logging:
#       driver: json-file

#   db-service:
#     build: backend/db-service
#     container_name: db-service
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./backend/db-service/src/db:/app/src/db
#     networks:
#       - monitoring
#     logging:
#       driver: json-file

#   ping-pong-service:
#     build: backend/ping-pong-service
#     container_name: ping-pong-service
#     ports:
#       - "5500:5500"
#     networks:
#       - monitoring
#     logging:
#       driver: json-file

#   parcheesi-service:
#     build: backend/parcheesi-service
#     container_name: parcheesi-service
#     ports:
#       - "5555:5555"
#     networks:
#       - monitoring
#     logging:
#       driver: json-file

#   user-service:
#     build: backend/User-Service
#     container_name: user-service
#     ports:
#       - "5004:5004"
#     networks:
#       - monitoring
#     logging:
#       driver: json-file

#   # ---------------------------
#   # Prometheus & Grafana
#   prometheus:
#     image: prom/prometheus
#     container_name: prometheus
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
#     networks:
#       - monitoring

#   grafana:
#     image: grafana/grafana
#     container_name: grafana
#     ports:
#       - "4000:3000"
#     environment:
#       - GF_SECURITY_ADMIN_USER=admin
#       - GF_SECURITY_ADMIN_PASSWORD=admin
#     networks:
#       - monitoring
#     volumes:
#       - grafana_data:/var/lib/grafana

#   # ---------------------------
#   # Elasticsearch + Kibana
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
#     container_name: elasticsearch
#     environment:
#       - discovery.type=single-node
#       - xpack.security.enabled=false
#       - ES_JAVA_OPTS=-Xms1g -Xmx1g
#     ports:
#       - "9200:9200"
#     volumes:
#       - es_data:/usr/share/elasticsearch/data
#     networks:
#       - monitoring

#   kibana:
#     image: docker.elastic.co/kibana/kibana:8.15.0
#     container_name: kibana
#     depends_on:
#       - elasticsearch
#     environment:
#       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#     ports:
#       - "5601:5601"
#     networks:
#       - monitoring

#   # ---------------------------
#   # Logstash
#   logstash:
#     image: docker.elastic.co/logstash/logstash:8.15.0
#     container_name: logstash
#     depends_on:
#       - elasticsearch
#     entrypoint: /bin/bash -c "
#       until curl -s http://elasticsearch:9200 >/dev/null; do
#       echo 'Waiting for Elasticsearch...'
#       sleep 5
#       done
#       exec /usr/share/logstash/bin/logstash -f /usr/share/logstash/pipeline
#       "
#     ports:
#       - "5044:5044"
#       - "9600:9600"
#     volumes:
#       - ./logstash/pipeline:/usr/share/logstash/pipeline
#     networks:
#       - monitoring


#   # ---------------------------
#   # Filebeat
#   filebeat:
#     image: docker.elastic.co/beats/filebeat:8.15.0
#     container_name: filebeat
#     user: root
#     depends_on:
#       - logstash
#     volumes:
#       - /var/lib/docker/containers:/var/lib/docker/containers:ro
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#     networks:
#       - monitoring

# # ---------------------------
# volumes:
#   grafana_data:
#   prometheus_conf:
#     driver: local
#   es_data:

# networks:
#   monitoring:
#     driver: bridge




# version: "3.9"

services:
  # ---------------------------
  # Frontend
  frontend:
    build: ./frontend
    container_name: frontend
    # ports:
    #   - "3000:3000"
    depends_on:
      - auth-service
      - chat-service
      - dashboard-service
      - db-service
      - ping-pong-service
      - parcheesi-service
      - user-service
    networks:
      - monitoring
    volumes:
      - ./frontend:/app          # 👈 Mount your local source code
      - /app/node_modules
    logging:
      driver: json-file

   # Nginx Reverse Proxy
  nginx:
    build: ./nginx       
    container_name: nginx
    ports:
      - "443:443"         # HTTPS
      - "80:80"           # HTTP
    networks:
      - monitoring
    depends_on:
      - frontend
      - auth-service
      - chat-service
      - dashboard-service
      - db-service
      - ping-pong-service
      - parcheesi-service
      - gateway-service
      - user-service
    logging:
      driver: json-file
  # ---------------------------
  # Backend Services
  auth-service:
    build: backend/auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    networks:
      - monitoring
    environment:
      - SECRET_KEY=mysecretkey
    logging:
      driver: json-file

  chat-service:
    build: backend/chat-service
    container_name: chat-service
    ports:
      - "5003:5003"
    networks:
      - monitoring
    logging:
      driver: json-file

  dashboard-service:
    build: backend/dashboard-service
    container_name: dashboard-service
    ports:
      - "5002:5002"
    networks:
      - monitoring
    logging:
      driver: json-file

  db-service:
    build: backend/db-service
    container_name: db-service
    ports:
      - "5000:5000"
    volumes:
      - ./backend/db-service/src/db:/app/src/db
    networks:
      - monitoring
    logging:
      driver: json-file

  ping-pong-service:
    build: backend/ping-pong-service
    container_name: ping-pong-service
    ports:
      - "5500:5500"
    networks:
      - monitoring
    logging:
      driver: json-file

  parcheesi-service:
    build: backend/parcheesi-service
    container_name: parcheesi-service
    ports:
      - "5555:5555"
    networks:
      - monitoring
    logging:
      driver: json-file

  gateway-service:
    build: backend/gateway-service
    container_name: gateway
    ports:
      - "5006:5006"
    networks:
      - monitoring
    logging:
      driver: json-file
    volumes:
      - ./backend/gateway-service:/app          # 👈 Mount your local source code
      - /app/node_modules

  user-service:
    build: backend/User-Service
    container_name: user-service
    ports:
      - "5004:5004"
    networks:
      - monitoring
    logging:
      driver: json-file

  # ---------------------------
  # Prometheus & Grafana
#   prometheus:
#     image: prom/prometheus
#     container_name: prometheus
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
#     networks:
#       - monitoring

#   grafana:
#     image: grafana/grafana
#     container_name: grafana
#     ports:
#       - "4000:3000"
#     environment:
#       - GF_SECURITY_ADMIN_USER=admin
#       - GF_SECURITY_ADMIN_PASSWORD=admin
#     networks:
#       - monitoring
#     volumes:
#       - grafana_data:/var/lib/grafana

#   # ---------------------------
#   # Elasticsearch + Kibana
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
#     container_name: elasticsearch
#     environment:
#       - discovery.type=single-node
#       - xpack.security.enabled=false
#       - ES_JAVA_OPTS=-Xms1g -Xmx1g
#     ports:
#       - "9200:9200"
#     volumes:
#       - es_data:/usr/share/elasticsearch/data
#     networks:
#       - monitoring

#   kibana:
#     image: docker.elastic.co/kibana/kibana:8.15.0
#     container_name: kibana
#     depends_on:
#       - elasticsearch
#     environment:
#       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#     ports:
#       - "5601:5601"
#     networks:
#       - monitoring

#   # ---------------------------
#   # Logstash avec wait-for-elasticsearch
#   logstash:
#     image: docker.elastic.co/logstash/logstash:8.15.0
#     container_name: logstash
#     depends_on:
#       - elasticsearch
#     entrypoint: /bin/bash -c "until curl -s http://elasticsearch:9200 >/dev/null; do echo 'Waiting for Elasticsearch...' ; sleep 5; done; exec /usr/share/logstash/bin/logstash -f /usr/share/logstash/pipeline"
#     ports:
#       - "5044:5044"
#       - "9600:9600"
#     volumes:
#       - ./logstash/pipeline:/usr/share/logstash/pipeline
#     networks:
#       - monitoring

#   # ---------------------------
#   # Filebeat
#   filebeat:
#     image: docker.elastic.co/beats/filebeat:8.15.0
#     container_name: filebeat
#     user: root
#     depends_on:
#       - logstash
#     volumes:
#       - /var/lib/docker/containers:/var/lib/docker/containers:ro
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#     networks:
#       - monitoring

# # ---------------------------
# volumes:
#   grafana_data:
#   prometheus_conf:
#     driver: local
#   es_data:

networks:
  monitoring:
    driver: bridge

