// src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google'; // Default font from create-next-app
import './globals.css';
import Navbar from '@/components/layout/Navbar'; // <-- Import your Navbar
import Sidebar from '@/components/layout/Sidebar';

const inter = Inter({ subsets: ['latin'] });
const BG_URL = 'https://images6.alphacoders.com/134/1344450.jpeg';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`relative bg-cover bg-center bg-no-repeat`}
        style={{ backgroundImage: `url('${BG_URL}')` }}
      >
        {/* <div className="absolute inset-0 bg-black/40" /> */}
        <Sidebar />
        <Navbar /> {/* <-- Add your Navbar component here */}
        <main className="relative bg-cover bg-center bg-no-repeat"
        style={{ backgroundImage: `url('${BG_URL}')` }}
        >
          {children} {/* This renders the content of your page.tsx files */}
        </main>
      </body>
    </html>
  );
}