import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import { SettingsProvider } from "./context/settings/SettingsContext";
import { Toaster } from "react-hot-toast";
import { SocketProvider } from "./context/SocketContext";
import Notifications from "./components/Notifications";
import { InviteProvider } from "./context/InviteContext";
import { TreeTournamentProvider } from "./modes/tournament/context/TreeTournamentContext"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

<>

  <Toaster position="top-right" />
  
  <SettingsProvider>
    <SocketProvider>
      <InviteProvider>
      <Notifications />
        <TreeTournamentProvider>
              {children}
        </TreeTournamentProvider>
      </InviteProvider>
    </SocketProvider>
  </SettingsProvider>
  </>
  );
}
