input {
  beats {
    port => 5044
  }
}

filter {
  # Renommer le container_name en champ "service"
  mutate {
    rename => { "docker.container.name" => "service" }
  }

  # Optionnel : ajouter un tag si besoin
  mutate {
    add_field => { "environment" => "dev" }
  }
}

output {
  # Index par service
  if [service] =~ "auth-service" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "auth-logs-%{+YYYY.MM.dd}"
    }
  } else if [service] =~ "chat-service" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "chat-logs-%{+YYYY.MM.dd}"
    }
  } else if [service] =~ "dashboard-service" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "dashboard-logs-%{+YYYY.MM.dd}"
    }
  } else if [service] =~ "ping-pong-service" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "pingpong-logs-%{+YYYY.MM.dd}"
    }
  } else if [service] =~ "parcheesi-service" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "parcheesi-logs-%{+YYYY.MM.dd}"
    }
  } else if [service] =~ "user-service" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "user-logs-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "other-logs-%{+YYYY.MM.dd}"
    }
  }

  stdout { codec => rubydebug } # debug
}
